# -*- coding: utf-8 -*-
"""Project_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DetloR5QKkkajqJ5c56Zsz4ZrM4tGRDT
"""

import pandas as pd
import numpy as np

df = pd.read_csv('/content/food_delivery_data.csv')
df

# Print the total number of orders.
df['OrderID'].count()

#  Find the total revenue generated.
df['revenue'] = df['PricePerUnit'] * df['Quantity']
df['revenue'].sum()

#  Count how many orders were successfully delivered.
df[df['OrderStatus'] == 'Delivered']['OrderID'].count()

# Find how many orders were rated 5 stars.
df[df['Rating'] == 5]['OrderID'].count()

#  Print the name of customers who used "Cash" for payment.
df[df['PaymentMethod'] == 'Cash']['CustomerName']

# Find the city with the highest number of orders.
df.groupby('City')['OrderID'].count().sort_values(ascending = False).head(1)

# How many "Burger" items were ordered in total?
df_burger = df[df['FoodItem'] == 'Burger']
df_burger['Quantity'].sum()

# Find the average delivery time.
df['DeliveryTimeMins'].mean()

#  List all unique food items.
df['FoodItem'].unique()